INSERT INTO CATEGORIAS(CATEGORIA) VALUES( 'INFORMATICA');
INSERT INTO CATEGORIAS(CATEGORIA) VALUES( 'ELETRODOMESTICOS');

INSERT INTO PRODUTOS (DESCRICAO,FOTO, PRECO, PRODUTO, QUANTIDADE, CATEGORIA_ID) VALUES ( 'MOUSE OPTICO', 'XXV', 35.20, 'MOUSE', 100, 1);


INSERT INTO CLIENTES  (BAIRRO,CEP,CIDADE,EMAIL, ESTADO ,RUA,SENHA ) VALUES ('CALIFORNIA', '262216010', 'NOVA IGUACU', 'MARCELO.AMORA@GMAIL.COM', 'RJ', 'ADELIA CHAVES 51 201', '1234');

INSERT INTO PEDIDOS(DATA, SESSAO, STATUS,CLIENTE_ID ) VALUES ('2019-05-05 18:00:00', 'XYZ', 'ANDAMENTO',1);

INSERT INTO PEDIDOITENS (PRODUTO, QUANTIDADE, SUBTOTAL,VALOR ,PEDIDO_ID, PRODUTO_ID ) VALUES ('MOUSE OPTICO', 10, 85.20, 8.25, 1, 1 );